-- Seed data for testing
-- Note: This should be run after the migrations

-- Insert test admin user (you'll need to create this user in Supabase Auth first)
-- Then update the profile to admin
-- UPDATE profiles SET role = 'admin' WHERE email = 'admin@example.com';

-- Sample test data comments
-- This file can be used to insert sample resumes, test users, etc.
-- For now, we keep it minimal as real data will come from the application

-- Example: Insert a test team
-- INSERT INTO teams (name, owner_id) VALUES
--   ('Test Company', 'user-uuid-here');

-- Note: Actual user creation must be done through Supabase Auth
-- The trigger will automatically create a profile when a user signs up

-- You can add sample resumes here for testing semantic search
-- But embeddings need to be generated by the application

